version: "3"
services:
  # APP
  toybank:
    container_name: challenge_toybank
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:15432/toybankdb?currentSchema=toybank&stringtype=unspecified&ApplicationName=toybank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_FLYWAY_SCHEMAS=toybank
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - toybank_network
  # PostgreSQL
  db:
    container_name: challenge_toybankdb
    image: postgres:12.3-alpine
    #volumes:
    #  - toybank_db:/var/lib/postgresql/data
    expose:
      - 15432
    ports:
      - 15432:15432
    command:
      -p 15432
    environment:
      - POSTGRES_DB=toybankdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - toybank_network
volumes:
  toybank_db:
networks:
  toybank_network:
    driver: bridge