CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ID                   UUID           NOT NULL,
    REFERENCE_ACCOUNT    UUID           NULL,
    IBAN                 TEXT UNIQUE    NOT NULL,
    BALANCE              NUMERIC(10, 2) NOT NULL DEFAULT 0,
    ANNUAL_INTEREST_RATE NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CURRENCY             TEXT           NOT NULL DEFAULT 'EUR',
    TYPE                 TEXT           NOT NULL,
    LOCKED               BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT           TIME           NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (REFERENCE_ACCOUNT) REFERENCES ACCOUNT (ID),

    CHECK (BALANCE >= 0)
);


CREATE TABLE IF NOT EXISTS TRANSACTION
(
    ID           UUID           NOT NULL,
    FROM_ACCOUNT TEXT           NULL,
    TO_ACCOUNT   TEXT           NULL,
    AMOUNT       NUMERIC(10, 2) NOT NULL,
    CURRENCY     TEXT           NOT NULL DEFAULT 'EUR',
    CREATED_AT   TIME           NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),

    CHECK (AMOUNT > 0),
    CHECK (FROM_ACCOUNT IS NOT NULL OR TO_ACCOUNT IS NOT NULL)
);
